### ISSUE TITLE
Question: when running agent in docker, how does it "get host values"

### ISSUE THREAD

**Issue by rogierlommers** [henrygd/beszel#118]
When I run the agent in a docker container, how does it get data from the host itself? (like CPU usage, memory, etc.). I understand that it can get data from containers, because the docker socket is mounted, but I don't think a process running inside a container get get access to the host, right?

**Comment by henrygd** [comment]
I'm not an expert on that, but my assumption is that `/proc` and `/sys` have the same cpu and memory info as the host because docker containers use the host kernel. They would only show something different if you limited the resources of the container.

It doesn't have access to everything though, which is why we need to run the container in host network mode to see the host interfaces. And implementing #36 seems like it may require mounting the host's `/proc` to get access to stats for disks that aren't being used by the container.

**Comment by rogierlommers** [comment]
Thanks for your QUICK reply! And of course thanks for Beszel! I just replaced my prometheus/grafana stack with Beszel (on my home server). It's way better and more light-weight.

I used to run the agent on the host itself, but I prefer running it in a container. I want to be 100% sure that the agent inside the container reports the same values, so I ran the agent twice: one time on the host and one time in the container. The results are indeed the same. See below screenshots.

There is one thing though: how do I find out what volume I need to mount in order to get Disk I/O stats?

![Screenshot 2024-08-15 at 11 22 27](https://github.com/user-attachments/assets/a111fc52-a2ca-46c0-9aba-723b29326514)
![Screenshot 2024-08-15 at 11 22 32](https://github.com/user-attachments/assets/7ba3ef78-667e-499b-9dbf-45903a6abeb0)

**Comment by henrygd** [comment]
Check [this section of the readme](https://github.com/henrygd/beszel/blob/main/readme.md#finding-the-correct-filesystem) for instructions on finding the correct filesystem.

In the next release or two I'm planning to add support for multiple disks, which may require mounting the host's `/proc`. So that will be an alternative to manually defining the root filesystem. It should be able to pick it up automatically like the binary does.

I'll close this issue but let me know if you have any more questions.

**Comment by bigfactory** [comment]
May be this  only occur when the image is built through ```FROM scratch```
