### ISSUE TITLE
Question: Is it safe to host publicly behind a reverse proxy?

### ISSUE THREAD

**Issue by teleg85120** [henrygd/beszel#119]
If I host the app behind a reverse proxy (Nginx/Apache) is it safe to be hosted on a publicly available server if I attach an SSL certificate to the webserver?

**Comment by henrygd** [comment]
Yes, but of course it's always a good idea to take precautions where you can.

If you run the binary, I'd recommend running as a user that doesn't have access to any important files outside the scope of the application.

You can also disable password login to the web UI. Or just put an auth gateway like Authelia in front of the whole app without breaking functionality.

Even in the worst case scenario, if someone gains access to the hub and / or your private key, they can't use that to run commands on your remote systems.

Let me know if you have questions about anything specific.

**Comment by tolgahanakgun** [comment]
I try to use beszel with nginx reverse proxy with HTTP Basic Authentication. However, it does not work. The client uses `Authorization` HTTP header to authenticate the client. Then, the browser sees that the header is already set and it does not override the `Authentication` header. This results `nginx` to return 401 like in the picture below:

![Image](https://github.com/user-attachments/assets/51c59833-31fa-4f81-b438-c5f00e7ed1d4)

 The requests with `200` HTTP code have `Authentication: Basic abcdef==` and succeeds. However, the other requests fail with `401` because the header is like`Authorization: $beszel_token`, not the one that nginx uses to authenticate:

 Is it possible to use another HTTP header like `X-Api-Key` for authentication like described here https://niravko.com/blog/auth_multiplexing/auth_multiplexing ?

**Comment by tolgahanakgun** [comment]
I am not familiar with the architecture of beszel and javascript but if this is enforced by pocketbase then it seems that this topic was already discussed and marked as unplanned https://github.com/pocketbase/pocketbase/issues/4163.

**Comment by leonjza** [comment]
> You can also disable password login to the web UI. Or just put an auth gateway like Authelia in front of the whole app without breaking functionality.

Sorry for commenting on an already closed issue, but for this scenario, do you have an example Authelia config (or similar) you can share?

I'm currently trying to get Beszel working with password auth disabled whith Authelia used as Traefik forwardauth to authenticate requests to Beszel. However, I'm seeing similar things to what @tolgahanakgun described, where it looks like the authentication header is causing unexpected 401's.
