### ISSUE TITLE
[Feature Request] Temps Notification/Alert

### ISSUE THREAD

**Issue by speedrapide10** [henrygd/beszel#131]
Hello,

Could you please add temps sensors Notification/Alert.

Thank you for your great work 🦾

**Comment by henrygd** [comment]
@steveiliop56 You can give it a go if you want, but it's going to be fairly complicated and I can't guarantee that I'll merge.

It will probably require new UI components and updates to the alerts collection. If you have ideas on implementation then we can discuss it further.

Adding time thresholds for alerts (#93) is near the top of my list, and I was going to see if I could add this in the same release. But it's likely going to be a few weeks until I can get around to because I need to work on a project for a client :expressionless:

**Comment by steveiliop56** [comment]
No problem, I will try to make a solid base for the feature so you can customize/fix it as much as you want. I believe it's going to be some copy pasta from the other notifications you have right?

**Comment by henrygd** [comment]
It depends on the implementation. If the alert is based on a single temperature and triggers if any sensor exceeds that temperature, then it will be pretty easy to add. I could probably add it and release it this week.

If we want to let the user choose which sensors to monitor and set custom thresholds for each sensor, that's going to require more work on both the front end and back end.

My thought is that most people would want the latter, but maybe I'm wrong.

**Comment by steveiliop56** [comment]
I was thinking we set an 80 C threshold for everything because if anything goes over 80 degrees on your machine I think you have an issue lol.

**Comment by steveiliop56** [comment]
@henrygd unfortunately I don't have any time to work on this feature, sorry. You can take over since you will get it done faster than me lol.

**Comment by henrygd** [comment]
Added in 0.6.0.

Let me know if you have any issues with it.
