### ISSUE TITLE
Some questions about how the project works

### ISSUE THREAD

**Issue by steveiliop56** [henrygd/beszel#134]
Hello,

I am learning go and I am impressed with your project and I want to learn how to make a react web server with go just like you did. I looked at the code and couldn't really understand how go serves/renders the react web page. Can you please explain me how this is done so I can play with it myself too?

Thanks in advance and sorry for filling your issues tab without an issue.

**Comment by steveiliop56** [comment]
Ok nvm did some more digging and understand how it's working thanks to this: https://react.dev/learn/add-react-to-an-existing-project Again awesome project!

**Comment by henrygd** [comment]
Thanks. It's just a static SPA build using Vite that's embedded into the binary. It doesn't need to be React, you can use Svelte or anything else.

The hub uses Echo to serve the files, because it's included in PocketBase, but you can also just use the native Go http server.

Here's more info on embedding: https://www.iamyadav.com/blogs/a-guide-to-embedding-static-files-in-go

**Comment by steveiliop56** [comment]
Thank you very much!
