### ISSUE TITLE
Disk usage shows 0% on an Unraid system

### ISSUE THREAD

**Issue by death4444** [henrygd/beszel#143]
system: unraid 6.12.11
What I want to monitor is the usage of one of the 120G SSD drives in the disk group.
df、fdisk、lsblk，Tried all three ways, no status information either way
![image](https://github.com/user-attachments/assets/fd35b57e-a6e4-490c-b3cf-32447f63e9f9)
![image](https://github.com/user-attachments/assets/09bd4165-5cc7-42bb-96d7-4c3d0eb34604)

df:
![image](https://github.com/user-attachments/assets/c9edf252-fea4-40c3-a0df-694ccc651b03)
FILESYSTEM: disk1

fdisk:
![image](https://github.com/user-attachments/assets/c09d53c6-2c1f-4334-89af-c6f377b7a1d6)
FILESYSTEM: /dev/sde1

lsblk:
![image](https://github.com/user-attachments/assets/ee11d6b0-34be-493f-b802-87d6479f588f)
FILESYSTEM: /sde/sde1

I don't know what to do to make it work？

**Comment by henrygd** [comment]
Hello, I'm about to go to sleep so won't follow up until tomorrow.

The `FILESYSTEM` option is just for the I/O chart, not usage. From your screenshots, it looks like `/dev/sde1`, `sde1`, or `sde` should work for that. 

`df` says `/mnt/disk1` is only using 128 bytes, so that's probably why the usage chart shows 0%. What filesystem is the container using?

**Comment by death4444** [comment]
have a good dream，my filesystem is zfs and no raid

**Comment by henrygd** [comment]
Usage shown in beszel is specifically for the mountpoint associated with the container storage.

That seems to be `/mnt/disk1`, which is reporting only 128 KB used according to `df`. I guess because all that's directly in `/mnt/disk1` are other mountpoints.

I don't know enough about unraid or zfs to tell you exactly how this can be solved. Maybe by changing the location of the container storage through the unraid interface?

I tagged this as 'help wanted' and will ask in the unraid discussion thread (#52) if anyone else ran into this.

**Comment by death4444** [comment]
thanks，I will try
