### ISSUE TITLE
Unable to see Docker data

### ISSUE THREAD

**Issue by Mark-2445** [henrygd/beszel#151]
Hi, while running Beszel Agent (Docker) on a Raspberry Pi, I cannot see any of the Docker information.

Beszel agent log shows the following for every container: 2024/09/02 19:08:42 Error getting container stats: beszel-agent - invalid data. 

Unfortunately the log does not state any further info.

**Comment by henrygd** [comment]
See here: [Docker container charts are empty or missing](https://github.com/henrygd/beszel/blob/main/readme.md#docker-container-charts-are-empty-or-missing)

**Comment by Mark-2445** [comment]
Hi, unfortunately that did not solve my issue - however I think its a Docker issue rather than a Beszel issue as whenever I run docker stats I don't see any memory info.

**Comment by henrygd** [comment]
Sorry to prod, but did you reboot after making the changes? This has come up a handful of times for pi users and that solution has worked every time so far.

I'm going to close the issue since it's not fixable on this end. If you do figure it out, please give me an update so I'll know for the future, thanks.
