### ISSUE TITLE
Charts layout grid/full error with new extra Filesystems

### ISSUE THREAD

**Issue by s4msy** [henrygd/beszel#158]
Looks like this is a bug between the two new features...

The new Feature of adding extra Filesystems adds two new graphs but they are not going in full view, they remain in grid view.
Vers. 0.3.0

![grafik](https://github.com/user-attachments/assets/da5e1474-1113-4507-8aae-7ec7151b4409)

**Comment by henrygd** [comment]
I forced them side by side because I thought it would take up too much space if people are monitoring lots of devices.

I have no problem changing them to follow the chosen layout, though.

Maybe best would be to combine the two charts into one card so it's easier to tell that they're the same device?

**Comment by henrygd** [comment]
Changed extra disk charts to follow grid settings in 0.4.0 :+1:
