### ISSUE TITLE
[BUG] Graph interruption

### ISSUE THREAD

**Issue by mariushosting** [henrygd/beszel#177]
![notcons](https://github.com/user-attachments/assets/c2fdf1cb-6abd-4440-a728-4726512bd6aa)

Docker CPU Usage and Docker Memory Usage are interrupted from time to time and the graph looks bugged.

**Comment by henrygd** [comment]
Hi Marius,

This is a known issue and seems to happen only on machines running Docker Engine 24 / API 1.43 or earlier.

It can be fixed by upgrading Docker.

Unfortunately, it remains an issue with Synology because Container Manager is locked to older versions, as you know.

Just to rule something else out, can you tell me your output of `docker info | grep -i cgroup`?

I can try to test the older Docker version in a VM at some point to see if it's fixable on this end, but it may be a while.

**Comment by mariushosting** [comment]
Thank you for confirming Henry. Docker Engine 24.
