### ISSUE TITLE
Min password length mismatch between `beszel admin` and the web UI

### ISSUE THREAD

**Issue by giorgiga** [henrygd/beszel#277]
I just noticed that `beszel admin create email@example.com password` accepts passwords of 8 characters or longer, but then the login page in the web UI requires at least 10 characters.

**Comment by henrygd** [comment]
I didn't realize that the admin command allows you to use 8 character passwords.

I tested again and the API still requires 10 character passwords for creation of admin accounts. As does the PocketBase web UI.

And the author of PocketBase [says 10 characters is the minimum](https://github.com/pocketbase/pocketbase/issues/3300#issuecomment-1716088126).

So it's an inconsistency, but it doesn't break anything. You can use the 8 character password to log in.

This is native PocketBase functionality and not something I want to override on this end. It could also be intentional for some reason. I'd recommend asking in PocketBase discussions.
