### ISSUE TITLE
Missing time label in graphs

### ISSUE THREAD

**Issue by durandguru** [henrygd/beszel#279]
Sometimes there is aan time label missing in graphs:

See the image. Al graphs except 1 has the label 18:30 missing
![image](https://github.com/user-attachments/assets/b312a804-0bee-472e-b8cf-71d1de4fe1bd)

**Comment by henrygd** [comment]
All graphs use the same component for the x axis, so they all have the same labels.

When one is missing like this, it's because the y axis is wider, causing the x axis to be narrower. There's a minimum gap required between ticks so sometimes that means one will be hidden.

You will see the label if you toggle off the grid display.

The only sure fix would be to make all charts have the same y axis width, and I don't think that's a good solution. So I'll try decreasing the minimum gap by a few pixels and maybe that will make this happen less often.
