### ISSUE TITLE
ARM server and Ipv6 only server issues

### ISSUE THREAD

**Issue by kattocloud** [henrygd/beszel#306]
Binary scripts don't seem to automatically determine the system kernel and install services based on a specific system kernel, which is problematic for ARM server support!
Also for Ipv6 only servers, it won't go live after installation!

**Comment by henrygd** [comment]
If the ipv6 problem is related to #288 then it will be fixed in the next release.

You can also build a binary with that fix by cloning the repo and running `make build-agent OS=linux ARCH=arm` in the `beszel` directory.

As for the install scripts, it should detect the proper architecture automatically. Is it downloading the wrong binary in your case?

What is your output of this command:

```bash
uname -m | sed 's/x86_64/amd64/' | sed 's/armv7l/arm/' | sed 's/aarch64/arm64/'
```
