### ISSUE TITLE
[Request] Suggestion of a slightly different layout

### ISSUE THREAD

**Issue by alex3305** [henrygd/beszel#31]
Hi @henrygd 👋 ,

Thanks for creating this nifty little tool. As you can probably tell I have been experimenting with it all day and enjoying it really well. One thing I have noticed is that the current layout has pretty low information density. This works really well on mobile, but perhaps not so on desktop. I think it would improve the project with very slight layout changes on larger screens. I have made some mockups to show what I mean:

![image](https://github.com/user-attachments/assets/359853ca-8c5c-4b05-aa13-6768f3442c7c)
![image](https://github.com/user-attachments/assets/471bd333-9f1e-4d3a-bbed-93e5db67036e)

Please let me know what you think.

And as a final question, maybe you could clarify what should be a discussion and what should be an issue?

**Comment by henrygd** [comment]
No problem, and thank you for asking that. I would like to use discussions for things like questions, suggestions, ideas, or feedback.

IMO something like this would be good as a discussion because others would be more likely to add their own opinions and we could work out a design that suits everyone well.

Maybe it would be good to make a "Design suggestions megathread" where anyone could toss out ideas?

In any case, thanks for your work on this, and I really like your changes. The only thing I'm not sold on is the "Add System" button being in the top bar on one page and not the other, causing the other buttons to move. Maybe we can just leave it there universally?

For the charts, I was split on whether to go with the 2x2 grid. I agree it's much better for getting a quick overview  of the system.

However I kind of like being able to vertically line up spikes with containers when one chart is above the other. What do you think about adding a small button or context menu option to change the grid size?

Maybe others can chime in with their opinions. I'm definitely not opposed to incorporating these changes.

**Comment by henrygd** [comment]
I made a thread for design change suggestions and added your post here: #56
