### ISSUE TITLE
Multiple disks label

### ISSUE THREAD

**Issue by codingmatty** [henrygd/beszel#350]
I have 10 external disks attached and the agent has picked them all up, but there is no way to label them, so I just have a bunch of sbX drives that are difficult to identify. I'm wondering if there is an easy way to label them somehow, even if its an environment variable with a bunch of key/value pairs or something

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

This change adds support for custom filesystem labels using environment variables. It modifies the agent to read labels from the FILESYSTEM_LABELS environment variable and updates the frontend to display these labels.

You can review changes in this commit: https://github.com/mark-addams001881/henrygd-beszel-350/commit/90a70a95c3b6feb0fcdbba579b23b93ce6f79eea.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by henrygd** [comment]
Let's move conversation about this to #294 since it's a similar issue.

I think the best option is to use label values straight from the disk if available. Maybe add a manual env var mapping if you don't want to use disk labels for whatever reason.

If you have time, can you run the agent with `LOG_LEVEL=debug` and check the line containing `DEBUG Disk I/O diskstats` that's logged on startup?

It should show info for your disks including labels. I just want to make sure those label values come through properly.
