### ISSUE TITLE
docker cpu usage empty when deploy on Cortex-A53 (4c/4t) arm cpu

### ISSUE THREAD

**Issue by xinmans** [henrygd/beszel#351]
beszel-agent  | 2024/12/30 09:31:01 ERROR Error getting container stats err="dockerproxy - no memory stats - see https://github.com/henrygd/beszel/issues/144"
beszel-agent  | 2024/12/30 09:31:01 ERROR Error getting container stats err="nginx-proxy-manager - no memory stats - see https://github.com/henrygd/beszel/issues/144"
beszel-agent  | 2024/12/30 09:31:01 ERROR Error getting container stats err="portainer_agent - no memory stats - see https://github.com/henrygd/beszel/issues/144"
beszel-agent  | 2024/12/30 09:31:01 ERROR Error getting container stats err="portainer - no memory stats - see https://github.com/henrygd/beszel/issues/144"
beszel-agent  | 2024/12/30 09:31:01 ERROR Error getting container stats err="watchtower - no memory stats - see https://github.com/henrygd/beszel/issues/144"
alpine:~/mydev/beszel#

**Comment by henrygd** [comment]
Look like a bug in Alpine / OpenRC. I'm going to close the issue since it's not something I can fix through Beszel, but I will try to help.

Here are a couple resources I found which may help:

https://gitlab.alpinelinux.org/alpine/aports/-/issues/15506

https://gitlab.alpinelinux.org/alpine/aports/-/issues/16282
